#!/bin/bash


function volume_notif(){
volume=$(pamixer --get-volume)
  if [ $volume -gt 50 ]
  then
    dunstify -a "volume level" -u low -r 9993 -h int:value:"${volume}%" -i volume-2 "Volume: ${volume}% $1" -t 2000
  else
    dunstify -a "volume level" -u low -r 9993 -h int:value:"${volume}%" -i volume-1 "Volume: ${volume}%" -t 2000
  fi
}



case $1 in 
up)
  pamixer -u 
  pamixer -i 5
  volume_notif 
  ;;
down)
  pamixer -u 
  pamixer -d 5  
  volume_notif
  ;;
mute)
  pamixer -t 
  if [ $( pamixer --get-mute ) ]
  then 
    dunstify "Volume" -t 2000 -r 9993 -u low "muted" 
  else
    ( pamixer -u )
    volume_notif
  fi 
  ;;
esac
